// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: src/proto/punto_venta.proto

package puntoventa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PuntoVentaService_GetPuntoVenta_FullMethodName = "/punto_venta.PuntoVentaService/GetPuntoVenta"
	PuntoVentaService_GetCufdActual_FullMethodName = "/punto_venta.PuntoVentaService/GetCufdActual"
	PuntoVentaService_ValidarCufd_FullMethodName   = "/punto_venta.PuntoVentaService/ValidarCufd"
)

// PuntoVentaServiceClient is the client API for PuntoVentaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PuntoVentaServiceClient interface {
	GetPuntoVenta(ctx context.Context, in *GetPuntoVentaRequest, opts ...grpc.CallOption) (*PuntoVentaResponse, error)
	GetCufdActual(ctx context.Context, in *GetCufdActualRequest, opts ...grpc.CallOption) (*CufdActualResponse, error)
	ValidarCufd(ctx context.Context, in *ValidarCufdRequest, opts ...grpc.CallOption) (*ValidarCufdResponse, error)
}

type puntoVentaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPuntoVentaServiceClient(cc grpc.ClientConnInterface) PuntoVentaServiceClient {
	return &puntoVentaServiceClient{cc}
}

func (c *puntoVentaServiceClient) GetPuntoVenta(ctx context.Context, in *GetPuntoVentaRequest, opts ...grpc.CallOption) (*PuntoVentaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PuntoVentaResponse)
	err := c.cc.Invoke(ctx, PuntoVentaService_GetPuntoVenta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puntoVentaServiceClient) GetCufdActual(ctx context.Context, in *GetCufdActualRequest, opts ...grpc.CallOption) (*CufdActualResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CufdActualResponse)
	err := c.cc.Invoke(ctx, PuntoVentaService_GetCufdActual_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puntoVentaServiceClient) ValidarCufd(ctx context.Context, in *ValidarCufdRequest, opts ...grpc.CallOption) (*ValidarCufdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidarCufdResponse)
	err := c.cc.Invoke(ctx, PuntoVentaService_ValidarCufd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PuntoVentaServiceServer is the server API for PuntoVentaService service.
// All implementations must embed UnimplementedPuntoVentaServiceServer
// for forward compatibility.
type PuntoVentaServiceServer interface {
	GetPuntoVenta(context.Context, *GetPuntoVentaRequest) (*PuntoVentaResponse, error)
	GetCufdActual(context.Context, *GetCufdActualRequest) (*CufdActualResponse, error)
	ValidarCufd(context.Context, *ValidarCufdRequest) (*ValidarCufdResponse, error)
	mustEmbedUnimplementedPuntoVentaServiceServer()
}

// UnimplementedPuntoVentaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPuntoVentaServiceServer struct{}

func (UnimplementedPuntoVentaServiceServer) GetPuntoVenta(context.Context, *GetPuntoVentaRequest) (*PuntoVentaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPuntoVenta not implemented")
}
func (UnimplementedPuntoVentaServiceServer) GetCufdActual(context.Context, *GetCufdActualRequest) (*CufdActualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCufdActual not implemented")
}
func (UnimplementedPuntoVentaServiceServer) ValidarCufd(context.Context, *ValidarCufdRequest) (*ValidarCufdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidarCufd not implemented")
}
func (UnimplementedPuntoVentaServiceServer) mustEmbedUnimplementedPuntoVentaServiceServer() {}
func (UnimplementedPuntoVentaServiceServer) testEmbeddedByValue()                           {}

// UnsafePuntoVentaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PuntoVentaServiceServer will
// result in compilation errors.
type UnsafePuntoVentaServiceServer interface {
	mustEmbedUnimplementedPuntoVentaServiceServer()
}

func RegisterPuntoVentaServiceServer(s grpc.ServiceRegistrar, srv PuntoVentaServiceServer) {
	// If the following call pancis, it indicates UnimplementedPuntoVentaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PuntoVentaService_ServiceDesc, srv)
}

func _PuntoVentaService_GetPuntoVenta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPuntoVentaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuntoVentaServiceServer).GetPuntoVenta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuntoVentaService_GetPuntoVenta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuntoVentaServiceServer).GetPuntoVenta(ctx, req.(*GetPuntoVentaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuntoVentaService_GetCufdActual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCufdActualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuntoVentaServiceServer).GetCufdActual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuntoVentaService_GetCufdActual_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuntoVentaServiceServer).GetCufdActual(ctx, req.(*GetCufdActualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuntoVentaService_ValidarCufd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidarCufdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuntoVentaServiceServer).ValidarCufd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuntoVentaService_ValidarCufd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuntoVentaServiceServer).ValidarCufd(ctx, req.(*ValidarCufdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PuntoVentaService_ServiceDesc is the grpc.ServiceDesc for PuntoVentaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PuntoVentaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "punto_venta.PuntoVentaService",
	HandlerType: (*PuntoVentaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPuntoVenta",
			Handler:    _PuntoVentaService_GetPuntoVenta_Handler,
		},
		{
			MethodName: "GetCufdActual",
			Handler:    _PuntoVentaService_GetCufdActual_Handler,
		},
		{
			MethodName: "ValidarCufd",
			Handler:    _PuntoVentaService_ValidarCufd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/punto_venta.proto",
}
