// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: src/proto/punto_venta.proto

package puntoventa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPuntoVentaRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nit              string                 `protobuf:"bytes,1,opt,name=nit,proto3" json:"nit,omitempty"`
	CodigoSucursal   string                 `protobuf:"bytes,2,opt,name=codigoSucursal,proto3" json:"codigoSucursal,omitempty"`
	CodigoPuntoVenta string                 `protobuf:"bytes,3,opt,name=codigoPuntoVenta,proto3" json:"codigoPuntoVenta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPuntoVentaRequest) Reset() {
	*x = GetPuntoVentaRequest{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuntoVentaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuntoVentaRequest) ProtoMessage() {}

func (x *GetPuntoVentaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuntoVentaRequest.ProtoReflect.Descriptor instead.
func (*GetPuntoVentaRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{0}
}

func (x *GetPuntoVentaRequest) GetNit() string {
	if x != nil {
		return x.Nit
	}
	return ""
}

func (x *GetPuntoVentaRequest) GetCodigoSucursal() string {
	if x != nil {
		return x.CodigoSucursal
	}
	return ""
}

func (x *GetPuntoVentaRequest) GetCodigoPuntoVenta() string {
	if x != nil {
		return x.CodigoPuntoVenta
	}
	return ""
}

type GetCufdActualRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nit              string                 `protobuf:"bytes,1,opt,name=nit,proto3" json:"nit,omitempty"`
	CodigoSucursal   string                 `protobuf:"bytes,2,opt,name=codigoSucursal,proto3" json:"codigoSucursal,omitempty"`
	CodigoPuntoVenta string                 `protobuf:"bytes,3,opt,name=codigoPuntoVenta,proto3" json:"codigoPuntoVenta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCufdActualRequest) Reset() {
	*x = GetCufdActualRequest{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCufdActualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCufdActualRequest) ProtoMessage() {}

func (x *GetCufdActualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCufdActualRequest.ProtoReflect.Descriptor instead.
func (*GetCufdActualRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{1}
}

func (x *GetCufdActualRequest) GetNit() string {
	if x != nil {
		return x.Nit
	}
	return ""
}

func (x *GetCufdActualRequest) GetCodigoSucursal() string {
	if x != nil {
		return x.CodigoSucursal
	}
	return ""
}

func (x *GetCufdActualRequest) GetCodigoPuntoVenta() string {
	if x != nil {
		return x.CodigoPuntoVenta
	}
	return ""
}

type ValidarCufdRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nit              string                 `protobuf:"bytes,1,opt,name=nit,proto3" json:"nit,omitempty"`
	CodigoSucursal   string                 `protobuf:"bytes,2,opt,name=codigoSucursal,proto3" json:"codigoSucursal,omitempty"`
	CodigoPuntoVenta string                 `protobuf:"bytes,3,opt,name=codigoPuntoVenta,proto3" json:"codigoPuntoVenta,omitempty"`
	Cufd             string                 `protobuf:"bytes,4,opt,name=cufd,proto3" json:"cufd,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidarCufdRequest) Reset() {
	*x = ValidarCufdRequest{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarCufdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarCufdRequest) ProtoMessage() {}

func (x *ValidarCufdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarCufdRequest.ProtoReflect.Descriptor instead.
func (*ValidarCufdRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{2}
}

func (x *ValidarCufdRequest) GetNit() string {
	if x != nil {
		return x.Nit
	}
	return ""
}

func (x *ValidarCufdRequest) GetCodigoSucursal() string {
	if x != nil {
		return x.CodigoSucursal
	}
	return ""
}

func (x *ValidarCufdRequest) GetCodigoPuntoVenta() string {
	if x != nil {
		return x.CodigoPuntoVenta
	}
	return ""
}

func (x *ValidarCufdRequest) GetCufd() string {
	if x != nil {
		return x.Cufd
	}
	return ""
}

type PuntoVentaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nit              string                 `protobuf:"bytes,1,opt,name=nit,proto3" json:"nit,omitempty"`
	CodigoSucursal   string                 `protobuf:"bytes,2,opt,name=codigoSucursal,proto3" json:"codigoSucursal,omitempty"`
	CodigoPuntoVenta string                 `protobuf:"bytes,3,opt,name=codigoPuntoVenta,proto3" json:"codigoPuntoVenta,omitempty"`
	Descripcion      string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	TipoPuntoVenta   string                 `protobuf:"bytes,5,opt,name=tipoPuntoVenta,proto3" json:"tipoPuntoVenta,omitempty"`
	Estado           string                 `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PuntoVentaResponse) Reset() {
	*x = PuntoVentaResponse{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuntoVentaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuntoVentaResponse) ProtoMessage() {}

func (x *PuntoVentaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuntoVentaResponse.ProtoReflect.Descriptor instead.
func (*PuntoVentaResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{3}
}

func (x *PuntoVentaResponse) GetNit() string {
	if x != nil {
		return x.Nit
	}
	return ""
}

func (x *PuntoVentaResponse) GetCodigoSucursal() string {
	if x != nil {
		return x.CodigoSucursal
	}
	return ""
}

func (x *PuntoVentaResponse) GetCodigoPuntoVenta() string {
	if x != nil {
		return x.CodigoPuntoVenta
	}
	return ""
}

func (x *PuntoVentaResponse) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *PuntoVentaResponse) GetTipoPuntoVenta() string {
	if x != nil {
		return x.TipoPuntoVenta
	}
	return ""
}

func (x *PuntoVentaResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type CufdActualResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codigo        string                 `protobuf:"bytes,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	CodigoControl string                 `protobuf:"bytes,2,opt,name=codigoControl,proto3" json:"codigoControl,omitempty"`
	FechaVigencia string                 `protobuf:"bytes,3,opt,name=fechaVigencia,proto3" json:"fechaVigencia,omitempty"`
	Transaccion   bool                   `protobuf:"varint,4,opt,name=transaccion,proto3" json:"transaccion,omitempty"`
	Existe        bool                   `protobuf:"varint,5,opt,name=existe,proto3" json:"existe,omitempty"` // true si existe, false si no tiene CUFD todavía
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CufdActualResponse) Reset() {
	*x = CufdActualResponse{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CufdActualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CufdActualResponse) ProtoMessage() {}

func (x *CufdActualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CufdActualResponse.ProtoReflect.Descriptor instead.
func (*CufdActualResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{4}
}

func (x *CufdActualResponse) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *CufdActualResponse) GetCodigoControl() string {
	if x != nil {
		return x.CodigoControl
	}
	return ""
}

func (x *CufdActualResponse) GetFechaVigencia() string {
	if x != nil {
		return x.FechaVigencia
	}
	return ""
}

func (x *CufdActualResponse) GetTransaccion() bool {
	if x != nil {
		return x.Transaccion
	}
	return false
}

func (x *CufdActualResponse) GetExiste() bool {
	if x != nil {
		return x.Existe
	}
	return false
}

type ValidarCufdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valido        bool                   `protobuf:"varint,1,opt,name=valido,proto3" json:"valido,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	FechaVigencia string                 `protobuf:"bytes,3,opt,name=fechaVigencia,proto3" json:"fechaVigencia,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarCufdResponse) Reset() {
	*x = ValidarCufdResponse{}
	mi := &file_src_proto_punto_venta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarCufdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarCufdResponse) ProtoMessage() {}

func (x *ValidarCufdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_punto_venta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarCufdResponse.ProtoReflect.Descriptor instead.
func (*ValidarCufdResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_punto_venta_proto_rawDescGZIP(), []int{5}
}

func (x *ValidarCufdResponse) GetValido() bool {
	if x != nil {
		return x.Valido
	}
	return false
}

func (x *ValidarCufdResponse) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *ValidarCufdResponse) GetFechaVigencia() string {
	if x != nil {
		return x.FechaVigencia
	}
	return ""
}

var File_src_proto_punto_venta_proto protoreflect.FileDescriptor

const file_src_proto_punto_venta_proto_rawDesc = "" +
	"\n" +
	"\x1bsrc/proto/punto_venta.proto\x12\vpunto_venta\"|\n" +
	"\x14GetPuntoVentaRequest\x12\x10\n" +
	"\x03nit\x18\x01 \x01(\tR\x03nit\x12&\n" +
	"\x0ecodigoSucursal\x18\x02 \x01(\tR\x0ecodigoSucursal\x12*\n" +
	"\x10codigoPuntoVenta\x18\x03 \x01(\tR\x10codigoPuntoVenta\"|\n" +
	"\x14GetCufdActualRequest\x12\x10\n" +
	"\x03nit\x18\x01 \x01(\tR\x03nit\x12&\n" +
	"\x0ecodigoSucursal\x18\x02 \x01(\tR\x0ecodigoSucursal\x12*\n" +
	"\x10codigoPuntoVenta\x18\x03 \x01(\tR\x10codigoPuntoVenta\"\x8e\x01\n" +
	"\x12ValidarCufdRequest\x12\x10\n" +
	"\x03nit\x18\x01 \x01(\tR\x03nit\x12&\n" +
	"\x0ecodigoSucursal\x18\x02 \x01(\tR\x0ecodigoSucursal\x12*\n" +
	"\x10codigoPuntoVenta\x18\x03 \x01(\tR\x10codigoPuntoVenta\x12\x12\n" +
	"\x04cufd\x18\x04 \x01(\tR\x04cufd\"\xdc\x01\n" +
	"\x12PuntoVentaResponse\x12\x10\n" +
	"\x03nit\x18\x01 \x01(\tR\x03nit\x12&\n" +
	"\x0ecodigoSucursal\x18\x02 \x01(\tR\x0ecodigoSucursal\x12*\n" +
	"\x10codigoPuntoVenta\x18\x03 \x01(\tR\x10codigoPuntoVenta\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\x12&\n" +
	"\x0etipoPuntoVenta\x18\x05 \x01(\tR\x0etipoPuntoVenta\x12\x16\n" +
	"\x06estado\x18\x06 \x01(\tR\x06estado\"\xb2\x01\n" +
	"\x12CufdActualResponse\x12\x16\n" +
	"\x06codigo\x18\x01 \x01(\tR\x06codigo\x12$\n" +
	"\rcodigoControl\x18\x02 \x01(\tR\rcodigoControl\x12$\n" +
	"\rfechaVigencia\x18\x03 \x01(\tR\rfechaVigencia\x12 \n" +
	"\vtransaccion\x18\x04 \x01(\bR\vtransaccion\x12\x16\n" +
	"\x06existe\x18\x05 \x01(\bR\x06existe\"k\n" +
	"\x13ValidarCufdResponse\x12\x16\n" +
	"\x06valido\x18\x01 \x01(\bR\x06valido\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\x12$\n" +
	"\rfechaVigencia\x18\x03 \x01(\tR\rfechaVigencia2\x8f\x02\n" +
	"\x11PuntoVentaService\x12S\n" +
	"\rGetPuntoVenta\x12!.punto_venta.GetPuntoVentaRequest\x1a\x1f.punto_venta.PuntoVentaResponse\x12S\n" +
	"\rGetCufdActual\x12!.punto_venta.GetCufdActualRequest\x1a\x1f.punto_venta.CufdActualResponse\x12P\n" +
	"\vValidarCufd\x12\x1f.punto_venta.ValidarCufdRequest\x1a .punto_venta.ValidarCufdResponseB\"Z src/proto/punto_venta;puntoventab\x06proto3"

var (
	file_src_proto_punto_venta_proto_rawDescOnce sync.Once
	file_src_proto_punto_venta_proto_rawDescData []byte
)

func file_src_proto_punto_venta_proto_rawDescGZIP() []byte {
	file_src_proto_punto_venta_proto_rawDescOnce.Do(func() {
		file_src_proto_punto_venta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_punto_venta_proto_rawDesc), len(file_src_proto_punto_venta_proto_rawDesc)))
	})
	return file_src_proto_punto_venta_proto_rawDescData
}

var file_src_proto_punto_venta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_proto_punto_venta_proto_goTypes = []any{
	(*GetPuntoVentaRequest)(nil), // 0: punto_venta.GetPuntoVentaRequest
	(*GetCufdActualRequest)(nil), // 1: punto_venta.GetCufdActualRequest
	(*ValidarCufdRequest)(nil),   // 2: punto_venta.ValidarCufdRequest
	(*PuntoVentaResponse)(nil),   // 3: punto_venta.PuntoVentaResponse
	(*CufdActualResponse)(nil),   // 4: punto_venta.CufdActualResponse
	(*ValidarCufdResponse)(nil),  // 5: punto_venta.ValidarCufdResponse
}
var file_src_proto_punto_venta_proto_depIdxs = []int32{
	0, // 0: punto_venta.PuntoVentaService.GetPuntoVenta:input_type -> punto_venta.GetPuntoVentaRequest
	1, // 1: punto_venta.PuntoVentaService.GetCufdActual:input_type -> punto_venta.GetCufdActualRequest
	2, // 2: punto_venta.PuntoVentaService.ValidarCufd:input_type -> punto_venta.ValidarCufdRequest
	3, // 3: punto_venta.PuntoVentaService.GetPuntoVenta:output_type -> punto_venta.PuntoVentaResponse
	4, // 4: punto_venta.PuntoVentaService.GetCufdActual:output_type -> punto_venta.CufdActualResponse
	5, // 5: punto_venta.PuntoVentaService.ValidarCufd:output_type -> punto_venta.ValidarCufdResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_punto_venta_proto_init() }
func file_src_proto_punto_venta_proto_init() {
	if File_src_proto_punto_venta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_punto_venta_proto_rawDesc), len(file_src_proto_punto_venta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_punto_venta_proto_goTypes,
		DependencyIndexes: file_src_proto_punto_venta_proto_depIdxs,
		MessageInfos:      file_src_proto_punto_venta_proto_msgTypes,
	}.Build()
	File_src_proto_punto_venta_proto = out.File
	file_src_proto_punto_venta_proto_goTypes = nil
	file_src_proto_punto_venta_proto_depIdxs = nil
}
